### ISSUE TITLE
Stubby Unable to Set `localhost` DNS

### ISSUE THREAD

**Issue by UpperCenter** [Sinodun/Stubby_Manager#5]
Hi All,

Apologies if this is a simple issue, but I'm unable to get Stubby to connect to any DNS servers. Application logs are:
```
Fri Feb 25 20:07:35 2022:  Action: Setting system to use Stubby service (setting DNS to localhost...)
Fri Feb 25 20:07:36 2022:  Status: Stubby service NOT in use by system (DNS settings NOT using localhost).
Fri Feb 25 20:07:56 2022:  WARNING: Stubby timed out trying to complete an action
```

My system is set to use `localhost` as the DNS server, so I'm unsure why the service is failing here.

![image](https://user-images.githubusercontent.com/46819924/155791802-e50ef1ca-8e63-490e-8f50-c9d15bd77178.png)
---
![image](https://user-images.githubusercontent.com/46819924/155791972-3a665e26-5593-4d26-a67b-82cfd74af7bb.png)

So far I've tried reinstalling the application, and reseting my network settings.

Running Windows 11 Pro

**Comment by saradickinson** [comment]
Hi there - so Stubby Manager is a bit dumb when it comes to trying to set localhost for the _interfaces_... Under the hood it blindly tries to set up for all 'physical' _interfaces_ via a Powershell script `StubbySetDns.ps1` which is installed on your machine in `C:\Program Files (x86)\Stubby` (so you can try running it manually if you like or even hacking it):
https://github.com/Sinodun/Stubby_Manager/blob/develop/os/windows/StubbySetDns.ps1

Stubby then double checks the state of all active _networks_ and I **think** the problem is it treats the VMware adapter as an active _network_ for this check, but the underlying _interface_ probably doesn't get set to Localhost by the above script because it is not physical?

I suspect if you do a Connection Test it might work because you Ethernet/Wifi connections are using localhost? You can take a look in the Logs tab to see what connections Stubby is actually making. We need to add some intelligence to the UI to select which specific interfaces Stubby should control otherwise it can end up in this inconsistent state on some devices....

**Comment by UpperCenter** [comment]
Thanks for the info, it does seem to work just fine even if it does just stay on "updating"
